apiVersion: v1
kind: ConfigMap
metadata:
  name: globalreserve-remote-config
  namespace: globalreserve-ut
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: globalreserve-remote-scheduler
    leaderElection:
      leaderElect: true
      lockObjectName: globalreserve-remote-scheduler
      lockObjectNamespace: globalreserve-ut
    plugins:
      reserve:
        enabled:
        - name: "global-resource-reserve-plugin"
      unreserve:
        enabled:
        - name: "global-resource-reserve-plugin"
    pluginConfig:
    - name: "global-resource-reserve-plugin"
      args:
        remote-url: "http://3rdparty-scheduler-pod:23456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalreserve-remote-scheduler
  namespace: globalreserveut
  labels:
    component: globalreserve-remote-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: globalreserve-remote-scheduler
  template:
    metadata:
      labels:
        component: globalreserve-remote-scheduler
    spec:
      serviceAccount: globalreserve-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: globalreserve-remote-config
      containers:
        - name: scheduler-ctrl
          image: globalreserve-scheduler:0.1
          imagePullPolicy: IfNotPresent
          args:
            - kube-globalreserve-scheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
            - --v=3
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes